apiVersion: metallb.io/v1beta1 
kind: IPAddressPool 
metadata: 
  name: main-pool 
  namespace: metallb-system 
spec: 
  addresses: 
  - http://10.48.10.107/24   #  <--- Change this to match the IP you were given 
